# Generated by Django 3.2.3 on 2021-05-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='status',
            field=models.CharField(choices=[('DI', 'Disponivel'), ('OC', 'Ocupado'), ('DE', 'Defeito')], default='DI', max_length=2),
        ),
    ]
