# Generated by Django 3.2.3 on 2021-05-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210518_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='qtd_estoque',
            field=models.PositiveIntegerField(),
        ),
    ]
