# Generated by Django 3.2.3 on 2021-05-18 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_qtd_estoque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='item',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='itens',
            field=models.ManyToManyField(to='core.Item'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pessoa_fisica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoafisica'),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pessoa_juridica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.pessoajuridica'),
        ),
    ]
