# Generated by Django 3.2.3 on 2021-05-18 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210518_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='equipamento',
            field=models.ManyToManyField(to='core.Equipamento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='itens',
            field=models.ManyToManyField(blank=True, null=True, to='core.Item'),
        ),
    ]
